// Generated by CoffeeScript 1.6.1
var init, map;

dojo.require("esri.map");

dojo.require("esri.arcgis.utils");

dojo.require("esri.dijit.Legend");

map = {};

init = function() {
  var webmapid;
  webmapid = "19d06f6ea88f4a53a55e504fae5061cd";
  return esri.arcgis.utils.createMap(webmapid, "mapDiv").then(function(response) {
    var legend;
    map = response.map;
    legend = new esri.dijit.Legend({
      map: map,
      layerInfos: esri.arcgis.utils.getLegendLayers(response)
    }, "legendDiv");
    return legend.startup();
  });
};

dojo.ready(init);
