import os
import sys
import time
need_blank = False
filename = sys.argv[1]

print("""\n.. DO NOT EDIT THIS FILE, automatically generated by
   extract_docs.py {date}\n\n""".format(date=time.asctime()))

print(os.path.basename(filename))
print("=" * len(os.path.basename(filename)))
print("")
for line in open(filename):
    if line.lstrip().startswith('#: '):
        print(line.lstrip()[3:].strip())
        need_blank = True
    else:
        if need_blank:
            print("")
            need_blank = False
